Adding 3.1.5 specific changes

diff --git a/images/airflow/3.1.5/bin/airflow-user/post-startup-script-verification b/images/airflow/3.1.5/bin/airflow-user/post-startup-script-verification
--- a/images/airflow/3.1.5/bin/airflow-user/post-startup-script-verification
+++ b/images/airflow/3.1.5/bin/airflow-user/post-startup-script-verification
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 echo "Executing post startup script verification"
 
-EXPECTED_AIRFLOW_VERSION="3.0.6"
+EXPECTED_AIRFLOW_VERSION="3.1.5"
 EXPECTED_WATCHTOWER_VERSION="3.4.0"
 
 validate_version_with_pip() {
@@ -11,9 +11,9 @@ validate_version_with_pip() {
   fi
 }
 
-if ! python3 -c 'import sys; assert sys.version_info[:2] == (3,12)' > /dev/null;
+if ! python3 -c 'import sys; assert sys.version_info[:2] == (3,13)' > /dev/null;
 then
-  echo "Validation Error: Python version 3.12 expected"
+  echo "Validation Error: Python version 3.13 expected"
 fi
 
 validate_version_with_pip "apache-airflow" "$EXPECTED_AIRFLOW_VERSION"
